name: Sync Template Files to asd-setup

on:
  push:
    branches: [main, master]
    paths:
      - 'asd-projects/**'
      - 'project-instructions/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-template-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout asd-projects-template
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout asd-setup repository
        uses: actions/checkout@v4
        with:
          repository: OperationSpark/asd-setup
          token: ${{ secrets.PAT }}
          path: asd-setup

      - name: Sync template files
        run: |
          set -x
          
          echo "Syncing template files from asd-projects-template to asd-setup..."
          
          # Remove existing template files
          rm -rf asd-setup/template-files
          
          # Create template-files directory
          mkdir -p asd-setup/template-files
          
          # Copy asd-projects if it exists
          if [ -d "asd-projects" ]; then
            echo "Copying asd-projects to template-files..."
            cp -r asd-projects asd-setup/template-files/
          else
            echo "Warning: asd-projects directory not found"
          fi
          
          # Copy project-instructions if it exists
          if [ -d "project-instructions" ]; then
            echo "Copying project-instructions to template-files..."
            cp -r project-instructions asd-setup/template-files/
          else
            echo "Warning: project-instructions directory not found"
          fi
          
          echo "Template files sync completed"

      - name: Check for changes in asd-setup
        id: check-changes
        run: |
          cd asd-setup
          git status
          if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes to asd-setup
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          cd asd-setup
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add template-files/
          git commit -m "chore: sync template files from asd-projects-template

          - Updated asd-projects from $(echo $GITHUB_SHA | cut -c1-7)
          - Synced project instructions
          - Auto-generated by GitHub Actions"
          git push

      - name: No changes detected
        if: steps.check-changes.outputs.changes == 'false'
        run: |
          echo "No changes detected in template files, skipping commit"